### ISSUE TITLE
Sharding uses too generic space 'operations' to store its data

### ISSUE THREAD

**Issue by racktear** [tarantool/shard#18]
Most of those spaces should be hidden:

```yaml
---
- sh_worker:
    temporary: false
    engine: memtx
  cluster_manager:
    temporary: false
    engine: memtx
  sharding:
    temporary: false
    engine: memtx
  operations:
    temporary: false
    engine: memtx
  sh_worker_vinyl:
    temporary: false
    engine: vinyl
...
```
